---
# Source: rafo-apache/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "rafo-apache-svc"
  namespace: "fuflo"
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
# Source: rafo-apache/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rafo-apache-deployment"
  namespace: "fuflo"
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app
  template:
    metadata:
      labels:
        app: httpd_app
        env: dev
    spec:
      containers:
        - name: "rafo-container-devops"
          image: httpd:latest
          ports:
            - containerPort: 80
---
# Source: rafo-apache/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "fuflo"
  labels:
    env: "dev"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"    # lower weights run earlier
    "helm.sh/hook-delete-policy": hook-succeeded