---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appNamePrefix }}-apache-deployment"
  namespace: default
  labels:
    env: {{ .Values.environment }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app
  template:
    metadata:
      labels:
        app: httpd_app
        env: {{ .Values.environment }}
    spec:
      containers:
        - name: "{{ .Values.appNamePrefix }}-container-devops"
          image: {{ .Values.image }}
          ports:
            - containerPort: 80