apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
  labels:
    env: "{{ .Values.environment }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"    # lower weights run earlier
    "helm.sh/hook-delete-policy": hook-succeeded