---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appNamePrefix }}-apache-svc"
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
